import { createPagesFunctionHandler } from "@react-router/cloudflare";

// @ts-ignore - the server build file is generated by `react-router build`
import * as build from "../build/server";

// @ts-ignore
export const onRequest = createPagesFunctionHandler({ build });
