import { createPagesFunctionHandler } from "@react-router/cloudflare";
import { RouterContextProvider } from "react-router";

// @ts-expect-error - the server build file is generated by `react-router build`
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: () => new RouterContextProvider(),
});
