name: Lint & TypeCheck
permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: TypeCheck
        run: pnpm run typecheck
