name: E2E Test
permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - ".github/**"
      - "LICENSE"
      - "renovate.json"
      - "CHANGELOG.md"
      - "**/README.md"
      - .gitignore
  push:
    branches:
      - main
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile

      - name: Build the extension
        run: pnpm --filter extension run build

      - name: Install Playwright Browsers
        run: pnpm --filter extension exec playwright install --with-deps chromium

      - name: Run Playwright tests
        run: pnpm run test:e2e
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
